spring:
  application:
    name: NauJavaPrjct
  datasource:
    url: jdbc:postgresql://localhost:5432/nau_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update